#ifndef ENUM_H
#define ENUM_H

enum ascii { BELL = 7, BACKSPACE, TAB, NEW_LINE, ENTER = 13, SPACE = 32 };
enum colors {
	BLACK, BLUE, GREEN, CYAN, RED, MAGENTA, BROWN,
	LIGHT_GREY, DARK_GREY, LIGHT_BLUE, LIGHT_GREEN, LIGHT_CYAN, LIGHT_RED, LIGHT_MAGENTA,
	YELLOW, WHITE
};
enum sizes { OPERATORS_SIZE = 3, WHITE_SPACES_SIZE = 6, SEPARATORS_SIZE = 9, BNF_INPUT_SIZE = 28};
enum argumentErrors { ARGUMENT_AMOUNT_ERROR, NUMBER_FORMAT_ERROR, TABULATION_LIMITS_ERROR, TABULATION_STEP_ERROR};
enum builderErrors { FILE_OPEN_ERROR, EMPTY_EXPRESSION_ERROR, UNRECOGNIZED_CHARACTER_ERROR, MISSING_OPERATOR_ERROR,
					 LOGARIPHM_FORMATTING_ERROR, COSINUS_FORMATTING_ERROR, UNRECOGNIZED_NUMBER_ERROR,
					 BRACKETS_FORMATTING_ERROR, OPERATOR_FORMATTING_ERROR };
enum operations { EMPTY, SUBSTITUTION, LOGARIPHM, COSINUS, MULTIPLICATION, ADDITION, SUBSTRACTION };
enum lexems { VARIABLE = 7, INVARIABLE, LEFT_BRACKET, RIGHT_BRACKET, END_OF_EXPRESSION };
enum separators { STAR, PLUS, MINUS, OPEN_BRACKET, CLOSE_BRACKET, X, L, C, DOT, DIGIT};

#endif